// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/zenoleg/shortener/internal/domain"
)

// WriteOnlyStorage is an autogenerated mock type for the WriteOnlyStorage type
type WriteOnlyStorage struct {
	mock.Mock
}

// Store provides a mock function with given fields: shortenURL
func (_m *WriteOnlyStorage) Store(shortenURL domain.ShortenURL) error {
	ret := _m.Called(shortenURL)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.ShortenURL) error); ok {
		r0 = rf(shortenURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWriteOnlyStorage creates a new instance of WriteOnlyStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriteOnlyStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *WriteOnlyStorage {
	mock := &WriteOnlyStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
