// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/zenoleg/shortener/internal/domain"
)

// writeOnlyStorage is an autogenerated mock type for the writeOnlyStorage type
type writeOnlyStorage struct {
	mock.Mock
}

// Store provides a mock function with given fields: ctx, shortenURL
func (_m *writeOnlyStorage) Store(ctx context.Context, shortenURL domain.ShortenURL) error {
	ret := _m.Called(ctx, shortenURL)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ShortenURL) error); ok {
		r0 = rf(ctx, shortenURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newWriteOnlyStorage creates a new instance of writeOnlyStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newWriteOnlyStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *writeOnlyStorage {
	mock := &writeOnlyStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
