// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/zenoleg/shortener/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// GetOriginalUseCase is an autogenerated mock type for the GetOriginalUseCase type
type GetOriginalUseCase struct {
	mock.Mock
}

// Do provides a mock function with given fields: ctx, url
func (_m *GetOriginalUseCase) Do(ctx context.Context, url domain.URL) (domain.URL, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 domain.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.URL) (domain.URL, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.URL) domain.URL); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(domain.URL)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.URL) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetOriginalUseCase creates a new instance of GetOriginalUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetOriginalUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetOriginalUseCase {
	mock := &GetOriginalUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
