// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/zenoleg/shortener/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// getOriginalUseCase is an autogenerated mock type for the getOriginalUseCase type
type getOriginalUseCase struct {
	mock.Mock
}

// Do provides a mock function with given fields: _a0
func (_m *getOriginalUseCase) Do(_a0 domain.URL) (domain.URL, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 domain.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.URL) (domain.URL, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(domain.URL) domain.URL); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.URL)
	}

	if rf, ok := ret.Get(1).(func(domain.URL) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newGetOriginalUseCase creates a new instance of getOriginalUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newGetOriginalUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *getOriginalUseCase {
	mock := &getOriginalUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
