// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/zenoleg/shortener/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// GetOriginalForRedirect is an autogenerated mock type for the GetOriginalForRedirect type
type GetOriginalForRedirect struct {
	mock.Mock
}

// Do provides a mock function with given fields: _a0
func (_m *GetOriginalForRedirect) Do(_a0 domain.ID) (domain.URL, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 domain.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.ID) (domain.URL, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(domain.ID) domain.URL); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.URL)
	}

	if rf, ok := ret.Get(1).(func(domain.ID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetOriginalForRedirect creates a new instance of GetOriginalForRedirect. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetOriginalForRedirect(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetOriginalForRedirect {
	mock := &GetOriginalForRedirect{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
