// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	usecase "github.com/zenoleg/shortener/internal/usecase"
)

// GetShort is an autogenerated mock type for the GetShort type
type GetShort struct {
	mock.Mock
}

// Do provides a mock function with given fields: ctx, query
func (_m *GetShort) Do(ctx context.Context, query usecase.GetShortURLQuery) (usecase.DestinationURL, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 usecase.DestinationURL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.GetShortURLQuery) (usecase.DestinationURL, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.GetShortURLQuery) usecase.DestinationURL); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(usecase.DestinationURL)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.GetShortURLQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetShort creates a new instance of GetShort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetShort(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetShort {
	mock := &GetShort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
